[package]
name = "partagi"
version = "0.1.0"
description = "Lightweight P2P screen sharing for small teams"
authors = ["Abdou"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.26"
futures-util = { version = "0.3.34", features = ["sink"] }
axum = "0.8.9"

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
xcap = "0.9"
cpal = "0.18"
image = { version = "0.25", default-features = false, features = ["jpeg"] }
